link_with ['Streamlyne-iOS-SDK']

platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'

post_install do |installer|
    installer.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ARCHS'] = "$(ARCHS_STANDARD_INCLUDING_64_BIT)"
        end
    end
end

